### ISSUE TITLE
Add Signet support

### ISSUE THREAD

**Issue by mcullan** [omnisat/lasereyes-mono#252]
We're hoping to replace our wallet handling with lasereyes but we use the Signet network for some testing and staging. 

Not all wallets support Signet but Xverse, Leather, and Unisat for sure do, so there would have to be some restrictions/constraints.

And I'd be interested in attempting this feature!

**Comment by hathbanger** [comment]
Thanks for opening an issue, @mcullan!!!!!

so, as it stands right now, we have support for mainnet, testnet, testnet4, signet, fractal, fractal testnet. with wallets that don't support signet out of the box, we leverage their existing testnet addresses and pubkeys that they return. There ARE some wallets that don't even support testnet, so in those cases, we'll need to build out some sort of map (perhaps in the providers or in SUPPORTED_WALLETS obj) that will let users impose said restrictions/constraints.

One of the saving graces here is that Memepool.space (the free, ip rate-limited api we use) has support for all of these networks, so the minutia we need to sort out are library behavior for unsupported wallets and a means to convey shortcomings for certain wallets.

You can give the current signet support a quick feel if you want by spinning up a quick next app w lasereyes baked in:

```bash
npx create-laseryes
```

then

```typescript
"use client";

import React, { ReactNode } from "react";
import { LaserEyesProvider, SIGNET } from "@omnisat/lasereyes";

export default function DefaultLayout({ children }: { children: ReactNode }) {
  return (
    <LaserEyesProvider config={{ network: SIGNET }}>
      {children}
    </LaserEyesProvider>
  );
}

```

I'll spend some time this week trying to surmise how we handle networks and switchNetwork for this wide variety of provided wallet methods and then we'll stick to it.

**Comment by hathbanger** [comment]
also, if you don't mind me asking, which project are you representing? I'd love to work closely with you guys to ensure we cover what you guys are looking for.

**Comment by mcullan** [comment]
> as it stands right now, we have support for mainnet, testnet, testnet4, signet, fractal, fractal testnet

Oh great! Are the docs up to date on that? If so, my mistake! But IIRC they just mentioned mainnet and testnet

**Comment by mcullan** [comment]
> which project are you representing?

I work with Inscribing Atlantis.  Right now we've been eyeing laser-eyes for [ephemera.gallery](https://ephemera.gallery), where we run an ongoing auction for our inscription series
